public class OpportunityEmailToBuyer {

    
    
    /*<p> We are ready to proceed with the purchase of {{{Opportunity.Year_from_Unit__c}}} {{{Opportunity.Manufacturer__c}}} {{{Recipient.Model__c}}} with {{{Opportunity.Hours_from_Units__c}}} hours and Serial Number {{{Opportunity.Unit_S_N__c}}} for {{{Opportunity.Offer_Amount__c}}}. You will find our tax exemption form attached for your records.</p>

<p></p>

<p>Please provide the following at your earliest convenience:</p>

<p>Your W-9 form - if you&rsquo;ve sent us one within the last year, you do not need to resend An invoice/bill of sale, 
which must include the following: Invoice to:  Zadoon, LLC  1268 Cronson Blvd, Bldg E  Crofton, MD 21114 Invoice from: 
Beneficiary Account Name Beneficiary Account full Address including Street, City, State, 
and Zip Beneficiary Phone Beneficiary Email Purchase Order # {{{Opportunity.Product__c}}} 
(Purchase Order # must be explicitly listed on invoice) Serial/VIN {{{Opportunity.Unit_S_N__c}}} 
(Serial/VIN must be explicitly listed on invoice) The verbiage, &quot;Machine is confirmed free and clear
of any and all liens and encumbrances&quot; If there is a lien, please provide a current payoff quote and 
point of contact for the lienholder Wire instructions: Bank Name Bank branch full Address including Street, 
City, State, and Zip Bank Routing Number (we need both ACH and Wire routing numbers) Bank Account Number Billing
Contact Name and Phone Number (we will be calling this contact to confirm wire instructions verbally to avoid wire fraud issues) 
Bank Representative Name and Phone Number (if available) The exact address and site contact of the machine (name and phone number) 
The size of the attachment (bucket, blade, etc.; dimensions and capacity please) Any known issues with the units being inspected Site requirements 

(PPE, hours of operation, check in procedure, etc.) *** note - all of our purchases are subject to inspection. 
If our inspection has already been conducted, this section does not apply. We will wire your funds after we&rsquo;ve 
inspected the unit. Your invoice secures the machine for Zadoon while we await the inspection. Please note that an 
unsatisfactory inspection may result in Zadoon rescinding or adjusting the offer amount.      Zadoon%20Tax%20Exemption%20Certificate.pdf</p>*/
 
    
}