public class EquipmentIronDemands {
/* 
    private List<Iron_Demand__c> IronDemands;
   
    private Equipment__c equipmentId; 
    
    public EquipmentIronDemands(ApexPages.StandardController controller) {
        this.equipmentId= (Equipment__c)controller.getRecord();
    }
    public List<Iron_Demand__c> getIronDemands()
    {
        
        IronDemands= [Select IronDemand_Contact__r.Name, IronDemand_Contact__r.MobilePhone, IronDemand_Contact__r.LeadSource, IronDemand_Contact__r.Client_Type_placeholder__c, CreatedDate  from Iron_Demand__c where IronDemand_Iron__c = :equipmentId.id];
        return IronDemands;
    }
   */
}